### ISSUE TITLE
Migrating tutorials to website todo

### ISSUE THREAD

**Issue by jni** [scikit-image/skimage-tutorials#57]
We now have the tutorials up at

https://scikit-image.org/skimage-tutorials/

To do:

- [ ] use myst or a plain .py [format supported by jupytext](https://jupytext.readthedocs.io/en/latest/formats.html) rather than nb as source. This just involves conversion of source files using nbconvert. Jupyter book should take care of the rest (But, [see reference](https://jupyterbook.org/file-types/jupytext.html)).
- [ ] add more tutorials to the full list. This is done by moving them from `lectures/not_yet_booked/` to `lectures`, updating `_toc.yml`, and ensuring that they build (no errors).
- [ ] Rename the repo to just `tutorials` so that the URL is scikit-image.org/tutorials
- [ ] (bigger) integrate with main site: look/theme, links from top navigation bar, etc.

**Comment by stefanv** [comment]
Very nice! @rossbar what pipeline did you use for NumPy / networkx?

**Comment by rossbar** [comment]
> what pipeline did you use for NumPy / networkx?

The tutorials sites for both NumPy and NetworkX use sphinx + the myst_nb extension directly rather than Jupyterbook. AIUI, jupyterbook is just a thin wrapper around the other executablebook tools (executablebooks/meta#285), giving a more user-friendly way of defining the `_toc` and `_config` for those who are not comfortable with sphinx. `myst-nb` + `jupytext` (for converting to myst text-based notebook format) should provide everything you need, but Jupyterbook is fine too - whether you prefer sphinx-style or jb-style config/organization is an individual preference!

**Comment by jni** [comment]
> for those who are not comfortable with sphinx

🙋‍♂️!

😝
